name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          cd Python
          pip install --target=Python -r requirements.txt
          cd ..

# current have package issues, will investigate later          
#      - name : Run tests 
#        run : |
#          pip install pytest
#          pytest
        
      - name: Zip Lambda function
        run: |
          cd Python
          zip -r ../lambda_function.zip *
          cd ..

      - name: Upload Lambda package to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
        run: |
          aws s3 cp lambda_function.zip s3://sudoku-repo/lambda_function.zip

      - name: Update Lambda function with S3 package
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
        run: |
          aws lambda update-function-code \
            --function-name Sudoku \
            --s3-bucket sudoku-repo \
            --s3-key lambda_function.zip

      - name: Prepare and publish a Lambda Layer for ortools
        run: |
          # Create a directory specifically for the ortools package and its dependencies
          mkdir -p ortools_deps/python/lib/python3.12/site-packages
          
          # Create a virtual environment outside of the packaging directory
          python -m venv ortools_venv
          source ortools_venv/bin/activate
          
          # Install ortools into the targeted directory within the layer packaging structure
          pip install -r ../Python/requirements-ortools.txt --target=ortools_deps/python/lib/python3.12/site-packages
          
          # Deactivate the virtual environment
          deactivate
          
          # Navigate to the ortools_deps directory
          cd ortools_deps
          
          # Zip only the necessary directory structure that should go into the Lambda Layer
          zip -r ../ortools_layer.zip python
          
          # Return to the root directory
          cd ..
          
          # Publish the zipped package as a Lambda Layer
          aws lambda publish-layer-version --layer-name ortools-layer --zip-file fileb://ortools_layer.zip --compatible-runtimes python3.12
        
      - name: Update Lambda function configuration to use the Layer
        run: |
          LAYER_VERSION_ARN=$(aws lambda list-layer-versions --layer-name ortools-layer --query 'LayerVersions[0].LayerVersionArn' --output text)
          aws lambda update-function-configuration --function-name Sudoku --layers $LAYER_VERSION_ARN

