name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          # Ensure the environment is activated
          source .venv/bin/activate

          # Install dependencies
          pip install --target=python -r requirements.txt

          # Zip the entire content of the python directory
          zip -r ../lambda_function.zip .

      - name: Upload Lambda function to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
        run: |
          aws lambda update-function-code --function-name Sudoku --zip-file fileb://lambda_function.zip
