name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          # Ensure the environment is activated
          source .venv/bin/activate

          # Install dependencies into a temporary directory
          mkdir -p python_tmp
          pip install --target=python -r requirements.txt

          # Add the application code to the deployment package
          cp -r * python_tmp/

          # Zip the entire content of the python directory
          cd python_tmp
          zip -r ../lambda_function.zip .
          cd ..

      - name: Upload Lambda function to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
        run: |
          aws lambda update-function-code --function-name Sudoku --zip-file fileb://lambda_function.zip
