name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          cd Python
          pip install --target=Python -r requirements.txt
          cd ..
          
      - name : Run tests 
        run : |
          cd Python
          pytest
          cd ..
        
      - name: Zip Lambda function
        run: |
          cd Python
          zip -r ../lambda_function.zip *
          cd ..

      - name: Upload Lambda function to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
        run: |
          aws lambda update-function-code --function-name Sudoku --zip-file fileb://lambda_function.zip
